#Retail Sales Performance Analysis

## Business Understanding

This project aims to analyze retail sales transactions to identify sales trends, customer behavior, regional performance, and factors influencing revenue generation.

#Data Loading

Load the dataset and inspect its structure

In [15]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("riyusingh/market-analysis-dataset")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/riyusingh/market-analysis-dataset/1.archive...

100%|██████████| 1.56M/1.56M [00:00<00:00, 109MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/riyusingh/market-analysis-dataset/versions/1

In [16]:
# Lihat isi folder
import os
print(os.listdir(path))

['market_basket_analysis_data.csv']

In [17]:
import pandas as pd

df = pd.read_csv(path + "/market_basket_analysis_data.csv")

df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Store_ID,Region,Product_Category,Product_Name,Brand,Quantity,Unit_Price,Discount,Total_Amount,Payment_Method,Basket_Size,Loyalty_Customer,Purchase_Time,Promotion_Applied,Weekend_Flag
0,T0,771319,2022-11-15,2137,East,Groceries,Product_A,Brand_Z,6,3976.67,0.26,17656.41,UPI,17,0,23:03,1,1
1,T1,970179,2025-04-10,3357,South,Groceries,Product_C,Brand_X,9,2063.91,0.05,17646.43,Cash,14,0,02:46,1,1
2,T2,660192,2023-11-29,6249,East,Electronics,Product_C,Brand_X,9,4684.22,0.29,29932.17,UPI,16,1,00:46,1,1
3,T3,800878,2024-11-30,5427,North,Electronics,Product_C,Brand_Y,7,4309.00,0.27,22018.99,Cash,7,1,17:28,1,0
4,T4,239043,2024-11-09,3883,East,Fashion,Product_A,Brand_Z,5,2284.72,0.45,6282.98,Wallet,15,1,12:12,1,1

#Data Understanding

In [18]:
df.shape

(50000, 18)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Transaction_ID     50000 non-null  object
 1   Customer_ID        50000 non-null  int64
 2   Transaction_Date   50000 non-null  object
 3   Store_ID           50000 non-null  int64
 4   Region             50000 non-null  object
 5   Product_Category   50000 non-null  object
 6   Product_Name       50000 non-null  object
 7   Brand              50000 non-null  object
 8   Quantity           50000 non-null  int64
 9   Unit_Price         50000 non-null  float64
 10  Discount           50000 non-null  float64
 11  Total_Amount       50000 non-null  float64
 12  Payment_Method     50000 non-null  object
 13  Basket_Size        50000 non-null  int64
 14  Loyalty_Customer   50000 non-null  int64
 15  Purchase_Time      50000 non-null  object
 16  Promotion_Applied  50000 non-null  int64
 17  Weekend_Flag       50000 non-null  int64
dtypes: float64(3), int64(7), object(8)
memory usage: 6.9+ MB

In [24]:
df.describe()

,Customer_ID,Store_ID,Quantity,Unit_Price,Discount,Total_Amount,Basket_Size,Loyalty_Customer,Promotion_Applied,Weekend_Flag
count,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,506096.375660,5033.662240,5.52538,2528.098656,0.249462,10481.747262,10.502320,0.498220,0.500060,0.498440
std,285319.499564,2853.407635,2.87077,1429.336518,0.144310,9004.509589,5.743345,0.500002,0.500005,0.500003
min,10012.000000,100.000000,1.00000,50.060000,0.000000,27.550000,1.000000,0.000000,0.000000,0.000000
25%,258689.500000,2570.000000,3.00000,1291.467500,0.120000,3263.125000,6.000000,0.000000,0.000000,0.000000
50%,507747.000000,5021.000000,6.00000,2519.965000,0.250000,7902.010000,10.000000,0.000000,1.000000,0.000000
75%,753705.500000,7484.000000,8.00000,3775.850000,0.370000,15459.567500,15.000000,1.000000,1.000000,1.000000
max,999974.000000,9999.000000,10.00000,4999.830000,0.500000,49366.940000,20.000000,1.000000,1.000000,1.000000

In [20]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Store_ID,Region,Product_Category,Product_Name,Brand,Quantity,Unit_Price,Discount,Total_Amount,Payment_Method,Basket_Size,Loyalty_Customer,Purchase_Time,Promotion_Applied,Weekend_Flag
0,T0,771319,2022-11-15,2137,East,Groceries,Product_A,Brand_Z,6,3976.67,0.26,17656.41,UPI,17,0,23:03,1,1
1,T1,970179,2025-04-10,3357,South,Groceries,Product_C,Brand_X,9,2063.91,0.05,17646.43,Cash,14,0,02:46,1,1
2,T2,660192,2023-11-29,6249,East,Electronics,Product_C,Brand_X,9,4684.22,0.29,29932.17,UPI,16,1,00:46,1,1
3,T3,800878,2024-11-30,5427,North,Electronics,Product_C,Brand_Y,7,4309.00,0.27,22018.99,Cash,7,1,17:28,1,0
4,T4,239043,2024-11-09,3883,East,Fashion,Product_A,Brand_Z,5,2284.72,0.45,6282.98,Wallet,15,1,12:12,1,1

In [22]:
df.isnull().sum()

Transaction_ID       0
Customer_ID          0
Transaction_Date     0
Store_ID             0
Region               0
Product_Category     0
Product_Name         0
Brand                0
Quantity             0
Unit_Price           0
Discount             0
Total_Amount         0
Payment_Method       0
Basket_Size          0
Loyalty_Customer     0
Purchase_Time        0
Promotion_Applied    0
Weekend_Flag         0
dtype: int64

In [23]:
df.duplicated().sum()

np.int64(0)

#Data Cleaning & Preparation

##menambahkan fitur baru untuk mengubah tanggal

In [25]:
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'])

In [26]:
df['Year'] = df['Transaction_Date'].dt.year
df['Month'] = df['Transaction_Date'].dt.month
df['Month_Name'] = df['Transaction_Date'].dt.month_name()

df['Hour'] = pd.to_datetime(
    df['Purchase_Time'],
    format='%H:%M'
).dt.hour

In [27]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Store_ID,Region,Product_Category,Product_Name,Brand,Quantity,Unit_Price,...,Payment_Method,Basket_Size,Loyalty_Customer,Purchase_Time,Promotion_Applied,Weekend_Flag,Year,Month,Month_Name,Hour
0,T0,771319,2022-11-15,2137,East,Groceries,Product_A,Brand_Z,6,3976.67,...,UPI,17,0,23:03,1,1,2022,11,November,23
1,T1,970179,2025-04-10,3357,South,Groceries,Product_C,Brand_X,9,2063.91,...,Cash,14,0,02:46,1,1,2025,4,April,2
2,T2,660192,2023-11-29,6249,East,Electronics,Product_C,Brand_X,9,4684.22,...,UPI,16,1,00:46,1,1,2023,11,November,0
3,T3,800878,2024-11-30,5427,North,Electronics,Product_C,Brand_Y,7,4309.00,...,Cash,7,1,17:28,1,0,2024,11,November,17
4,T4,239043,2024-11-09,3883,East,Fashion,Product_A,Brand_Z,5,2284.72,...,Wallet,15,1,12:12,1,1,2024,11,November,12

#Exploratory Data Analysis

In [39]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Store_ID,Region,Product_Category,Product_Name,Brand,Quantity,Unit_Price,...,Payment_Method,Basket_Size,Loyalty_Customer,Purchase_Time,Promotion_Applied,Weekend_Flag,Year,Month,Month_Name,Hour
0,T0,771319,2022-11-15,2137,East,Groceries,Product_A,Brand_Z,6,3976.67,...,UPI,17,0,23:03,1,1,2022,11,November,23
1,T1,970179,2025-04-10,3357,South,Groceries,Product_C,Brand_X,9,2063.91,...,Cash,14,0,02:46,1,1,2025,4,April,2
2,T2,660192,2023-11-29,6249,East,Electronics,Product_C,Brand_X,9,4684.22,...,UPI,16,1,00:46,1,1,2023,11,November,0
3,T3,800878,2024-11-30,5427,North,Electronics,Product_C,Brand_Y,7,4309.00,...,Cash,7,1,17:28,1,0,2024,11,November,17
4,T4,239043,2024-11-09,3883,East,Fashion,Product_A,Brand_Z,5,2284.72,...,Wallet,15,1,12:12,1,1,2024,11,November,12

##sales overview

In [30]:
total_revenue = df['Total_Amount'].sum()
total_transactions = df['Transaction_ID'].nunique()
total_quantity = df['Quantity'].sum()
avg_transaction = df['Total_Amount'].mean()

In [31]:
print(f"Total Revenue: {total_revenue:,.2f}")
print(f"Total Transactions: {total_transactions:,}")
print(f"Total Quantity Sold: {total_quantity:,}")
print(f"Average Transaction Value: {avg_transaction:,.2f}")

Total Revenue: 524,087,363.08
Total Transactions: 50,000
Total Quantity Sold: 276,269
Average Transaction Value: 10,481.75

##sales trend analysis

In [33]:
#revenue per month
monthly_sales = (
    df.groupby('Month_Name')['Total_Amount']
    .sum()
)

print(f"Bulan yang menghasilkan revenue tertinggi adalah {monthly_sales.idxmax()}")
print(f"Bulan yang menghasilkan revenue terendah adalah {monthly_sales.idxmin()}")

Bulan yang menghasilkan revenue tertinggi adalah March
Bulan yang menghasilkan revenue terendah adalah June

In [34]:
#revennue per region
region_revenue = df.groupby('Region')['Total_Amount'].sum()

print(f"Region yang menghasilkan revenue tertinggi adalah {region_revenue.idxmax()}")
print(f"Region yang menghasilkan revenue terendah adalah {region_revenue.idxmin()}")

Region yang menghasilkan revenue tertinggi adalah North
Region yang menghasilkan revenue terendah adalah East

In [35]:
#quantity per region
region_quantity = df.groupby('Region')['Quantity'].sum()

print(f"Region yang menghasilkan quantity tertinggi adalah {region_quantity.idxmax()}")
print(f"Region yang menghasilkan quantity terendah adalah {region_quantity.idxmin()}")

Region yang menghasilkan quantity tertinggi adalah North
Region yang menghasilkan quantity terendah adalah South

##product category analysis

In [37]:
#revenue per category
category_revenue = df.groupby('Product_Category')['Total_Amount'].sum()

print(f"Category yang menghasilkan revenue tertinggi adalah {category_revenue.idxmax()}")
print(f"Category yang menghasilkan revenue terendah adalah {category_revenue.idxmin()}")

Category yang menghasilkan revenue tertinggi adalah Electronics
Category yang menghasilkan revenue terendah adalah Fashion

In [38]:
#top product

product_revenue = df.groupby('Product_Name')['Total_Amount'].sum()

print(f"Product yang menghasilkan revenue tertinggi adalah {product_revenue.idxmax()}")
print(f"Product yang menghasilkan revenue terendah adalah {product_revenue.idxmin()}")

Product yang menghasilkan revenue tertinggi adalah Product_B
Product yang menghasilkan revenue terendah adalah Product_A

In [42]:
#top brand
brand_revenue = df.groupby('Brand')['Total_Amount'].sum()
top_brand = brand_revenue.idxmax()

#top category
category_revenue = df.groupby('Product_Category')['Total_Amount'].sum()
top_category = category_revenue.idxmax()

print(f"Brand yang menghasilkan revenue tertinggi adalah {top_brand}")
print(f"Category yang menghasilkan revenue tertinggi adalah {top_category}")

Brand yang menghasilkan revenue tertinggi adalah Brand_Z
Category yang menghasilkan revenue tertinggi adalah Electronics

##payment method analysis

In [46]:
df['Payment_Method'].unique()

array(['UPI', 'Cash', 'Wallet', 'Card'], dtype=object)

In [47]:
payment_method_revenue = df.groupby('Payment_Method')['Total_Amount'].sum()

print(f"Metode pembayaran yang menghasilkan revenue tertinggi adalah {payment_method_revenue.idxmax()}")
print(f"Metode pembayaran yang menghasilkan revenue terendah adalah {payment_method_revenue.idxmin()}")

Metode pembayaran yang menghasilkan revenue tertinggi adalah Wallet
Metode pembayaran yang menghasilkan revenue terendah adalah Cash

#loyalty customer analysis

In [50]:
df.groupby('Loyalty_Customer')['Total_Amount'].mean()

Loyalty_Customer
0    10458.199959
1    10505.462820
Name: Total_Amount, dtype: float64

##promotion analysis

In [51]:
df.groupby('Promotion_Applied')['Total_Amount'].mean()

Promotion_Applied
0    10507.022009
1    10456.478579
Name: Total_Amount, dtype: float64

##discount analysis

In [52]:
df[['Discount','Total_Amount']].corr()

              Discount  Total_Amount
Discount      1.000000     -0.215503
Total_Amount -0.215503      1.000000

In [54]:
df.groupby(pd.cut(df['Discount'],5))['Total_Amount'].mean()

/tmp/ipykernel_1987/4257959292.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(pd.cut(df['Discount'],5))['Total_Amount'].mean()

Discount
(-0.0005, 0.1]    13069.709100
(0.1, 0.2]        11898.808895
(0.2, 0.3]        10364.273149
(0.3, 0.4]         8976.778788
(0.4, 0.5]         7817.031570
Name: Total_Amount, dtype: float64

##time analysis

In [58]:
hour_performance = df.groupby('Hour')['Total_Amount'].sum()

print(f"Jam yang menghasilkan revenue tertinggi adalah {hour_performance.idxmax()}")
print(f"Jam yang menghasilkan revenue terendah adalah {hour_performance.idxmin()}")

Jam yang menghasilkan revenue tertinggi adalah 19
Jam yang menghasilkan revenue terendah adalah 6

In [57]:
df.groupby('Hour')['Total_Amount'].sum()

Hour
0     22529037.79
1     21792286.78
2     22682128.61
3     21736971.92
4     22155691.82
5     21676914.68
6     20571653.29
7     21508139.68
8     21054187.01
9     22259795.45
10    21948778.22
11    21787832.14
12    21526070.11
13    21571534.33
14    21861838.37
15    22513912.96
16    20661658.80
17    22796796.59
18    21517628.70
19    22903684.48
20    21997980.33
21    21753108.77
22    20855092.68
23    22424639.57
Name: Total_Amount, dtype: float64

In [60]:
weekend_flag = df.groupby('Weekend_Flag')['Total_Amount'].sum()
print(f"Weekend yang menghasilkan revenue tertinggi adalah {weekend_flag.idxmax()}")
print(f"Weekend yang menghasilkan revenue terendah adalah {weekend_flag.idxmin()}")

Weekend yang menghasilkan revenue tertinggi adalah 0
Weekend yang menghasilkan revenue terendah adalah 1

#simpan data

In [61]:
# Simpan ke CSV
df.to_csv('sales_cleaned.csv', index=False)

In [62]:
from google.colab import files

files.download('sales_cleaned.csv')